import React from 'react';
import { Edit2, Trash2, AlertCircle, TrendingUp, TrendingDown } from 'lucide-react';
import { PettyCashTransaction } from '../../types';

interface PettyCashTableProps {
  transactions: PettyCashTransaction[];
  onEditTransaction: (transaction: PettyCashTransaction) => void;
  onDeleteTransaction: (transactionId: string) => void;
}

export const PettyCashTable: React.FC<PettyCashTableProps> = ({
  transactions,
  onEditTransaction,
  onDeleteTransaction
}) => {
  const sortedTransactions = [...transactions].sort((a, b) => 
    new Date(b.date).getTime() - new Date(a.date).getTime()
  );

  return (
    <div className="overflow-x-auto">
      <table className="w-full text-sm text-right">
        <thead className="bg-gray-50">
          <tr>
            <th className="px-4 py-3 text-right font-medium text-gray-700">תאריך</th>
            <th className="px-4 py-3 text-right font-medium text-gray-700">תיאור</th>
            <th className="px-4 py-3 text-right font-medium text-gray-700">סוג</th>
            <th className="px-4 py-3 text-right font-medium text-gray-700">כניסה</th>
            <th className="px-4 py-3 text-right font-medium text-gray-700">סכום</th>
            <th className="px-4 py-3 text-right font-medium text-gray-700">פעולות</th>
          </tr>
        </thead>
        <tbody className="divide-y divide-gray-200">
          {sortedTransactions.map((transaction) => (
            <tr key={transaction.id} className="hover:bg-gray-50">
              <td className="px-4 py-3 text-gray-600">
                {new Date(transaction.date).toLocaleDateString('he-IL')}
              </td>
              <td className="px-4 py-3">
                <div className="flex items-center gap-2">
                  <span className="font-medium text-gray-900">{transaction.description}</span>
                  {transaction.isAutoGenerated && (
                    <AlertCircle className="h-4 w-4 text-blue-500" title="נוצר אוטומטית" />
                  )}
                </div>
              </td>
              <td className="px-4 py-3">
                <div className="flex items-center gap-2">
                  {transaction.type === 'income' ? (
                    <TrendingUp className="h-4 w-4 text-green-600" />
                  ) : (
                    <TrendingDown className="h-4 w-4 text-red-600" />
                  )}
                  <span className={`inline-flex px-2 py-1 text-xs rounded-full ${
                    transaction.type === 'income' 
                      ? 'bg-green-100 text-green-800' 
                      : 'bg-red-100 text-red-800'
                  }`}>
                    {transaction.type === 'income' ? 'הכנסה' : 'הוצאה'}
                  </span>
                </div>
              </td>
              <td className="px-4 py-3 text-gray-600">
                {transaction.entrance ? `כניסה ${transaction.entrance}` : 'כל הבניין'}
              </td>
              <td className="px-4 py-3">
                <span className={`font-medium ${
                  transaction.type === 'income' ? 'text-green-600' : 'text-red-600'
                }`}>
                  {transaction.type === 'income' ? '+' : '-'}{transaction.amount.toLocaleString()}₪
                </span>
              </td>
              <td className="px-4 py-3">
                <div className="flex items-center gap-2">
                  {!transaction.isAutoGenerated && (
                    <>
                      <button
                        onClick={() => onEditTransaction(transaction)}
                        className="p-1 text-blue-600 hover:bg-blue-100 rounded"
                        title="ערוך"
                      >
                        <Edit2 className="h-4 w-4" />
                      </button>
                      <button
                        onClick={() => onDeleteTransaction(transaction.id)}
                        className="p-1 text-red-600 hover:bg-red-100 rounded"
                        title="מחק"
                      >
                        <Trash2 className="h-4 w-4" />
                      </button>
                    </>
                  )}
                  {transaction.isAutoGenerated && (
                    <span className="text-xs text-gray-500">אוטומטי</span>
                  )}
                </div>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
      
      {transactions.length === 0 && (
        <div className="text-center py-8 text-gray-500">
          אין פעולות רשומות
        </div>
      )}
    </div>
  );
};