export interface Building {
  id: string;
  name: string;
  entrances: string[];
  elevatorCompany?: string;
  elevatorPhone?: string;
  electricityDetails?: {
    entrance: string;
    contractNumber: string;
    meterNumber: string;
  }[];
  entranceCodes?: {
    entrance: string;
    code: string;
  }[];
}

export interface Tenant {
  id: string;
  apartment: string;
  floor: number;
  name: string;
  ownershipStatus: 'owner' | 'renter';
  ownerName?: string;
  ownerPhone?: string;
  entrance: string;
  primaryPhone: string;
  secondaryPhone?: string;
  monthlyAmount: number;
  paymentMethod: 'cash' | 'credit';
  creditDay?: number;
  customAmount?: number;
  isDebtor: boolean;
}

export interface Payment {
  tenantId: string;
  month: number;
  year: number;
  paid: boolean;
  date?: string;
}

export interface Expense {
  id: string;
  date: string;
  description: string;
  category: string;
  amount: number;
  notes?: string;
  entrance?: string; // Added entrance field
  isAutoGenerated?: boolean;
  sourceType?: 'issue' | 'inventory' | 'electricity';
  sourceId?: string;
}

export interface PettyCashTransaction {
  id: string;
  date: string;
  description: string;
  type: 'income' | 'expense';
  amount: number;
  entrance?: string; // Added entrance field
  isAutoGenerated?: boolean;
}

export interface Employee {
  id: string;
  name: string;
  phone: string;
  startDate: string;
  baseSalary: number;
  workDaysPerMonth: number;
  absences: {
    id: string;
    date: string;
    reason: string;
  }[];
}

export interface Issue {
  id: string;
  date: string;
  reporterName: string;
  description: string;
  repairCost?: number;
  status: 'open' | 'in-progress' | 'resolved';
  notes?: string;
  entrance?: string; // Added entrance field
}

export interface Product {
  id: string;
  name: string;
  quantity: number;
  pricePerUnit: number;
}

export interface ProductUsage {
  id: string;
  productId: string;
  quantity: number;
  location: string;
  date: string;
  notes?: string;
  cost: number;
}

export interface ProductHistory {
  id: string;
  productId: string;
  date: string;
  action: 'add' | 'use' | 'create';
  quantity: number;
  location?: string;
  cost: number;
  notes?: string;
}

export interface ElectricityReading {
  id: string;
  buildingId: string;
  entrance: string;
  readingDate: string;
  meterReading: number;
  electricityCost?: number; // Added electricity cost field
  notes?: string;
}

export interface AppState {
  currentBuildingId: string;
  buildings: Building[];
  tenants: { [buildingId: string]: Tenant[] };
  payments: { [buildingId: string]: Payment[] };
  expenses: { [buildingId: string]: Expense[] };
  pettyCash: { [buildingId: string]: PettyCashTransaction[] };
  employees: Employee[]; // Changed from { [buildingId: string]: Employee[] } to Employee[]
  issues: { [buildingId: string]: Issue[] };
  products: Product[];
  productUsages: ProductUsage[];
  productHistory: ProductHistory[];
  electricityReadings: { [buildingId: string]: ElectricityReading[] };
  settings: {
    appTitle: string;
    tabOrder: string[];
    monthlyAmount: { [buildingId: string]: number };
    pettyCashTransfer: { [buildingId: string]: number };
    whatsappTemplate: string;
    accountantEmail?: string;
  };
}